output:
  file: "galaxy_tools.json"
processing:
  max_workers: 5
  tool_limit: 200 # Set to null for no limit

categories:
  Get Data:
    percentage: 1
  Astronomy:
    percentage: 1
  # Other categories not listed will fetch 100% of tools

comparison:
  eu_json_file: "galaxy_tools.json"
  bizon_server_json_file: "galaxy_tools_bizon.json"
  output_excel: "galaxy_tools_comparison.xlsx"

agent:
  # base_model: "intfloat/e5-base-v2"
  finetuned_model: "johnnas12/e5-galaxy-finetuned"
  tools_embeddings_path: "agents/embeddings/galaxy_embeddings_20251006_132713.npy"
  tools_metadata_path: "agents/embeddings/galaxy_metadata_20251006_132713.json"
  workflow_embeddings_path: "agents/embeddings/iwc_workflow_embeddings_20251006_113552.npy"
  workflow_metadata_path: "agents/embeddings/iwc_workflow_metadata_20251006_113552.json"