services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    container_name: mcp-app
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
      - MCP_PORT=${MCP_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=redis
      - QDRANT_HOST=qdrant
      - QDRANT_HTTP_PORT=${QDRANT_HTTP_PORT}
      - CURRENT_LLM=${CURRENT_LLM:-openai} # Set current LLM to run the MCP server with, defaults to openai.
      - MONGO_HOST=mongo
      - MONGO_PORT=${MONGO_PORT}
    ports:
      - "${APP_PORT}:8895" # Uvicorn
      - "${MCP_PORT}:8897" # bioblend_server
    depends_on:
      - redis
      - qdrant
      - mongo
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app            # Live code sync
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    container_name: redis
    command: ["redis-server", "--port", "${REDIS_PORT}"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    platform: linux/amd64
    container_name: qdrant
    environment:
      - QDRANT__SERVICE__HTTP_PORT=${QDRANT_HTTP_PORT}
      - QDRANT__SERVICE__GRPC_PORT=${QDRANT_GRPC_PORT}
    ports:
      - "${QDRANT_HTTP_PORT}:${QDRANT_HTTP_PORT}" # HTTP
      - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}" # gRPC
    volumes:
      - vectordata:/qdrant/storage
    restart: unless-stopped

  mongo:
    image: mongo:latest
    platform: linux/amd64
    container_name: mongo
    command: ["mongod", "--bind_ip_all", "--port", "${MONGO_PORT}"]
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  vectordata:
  redis_data:
  mongo_data: