[project]
name = "mcptrial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.4.1",
    "requests>=2.32.3",
    "beeai-framework==0.1.4",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"